"""Explicit mappings from composed control bundles to controller bindings."""

from __future__ import annotations

from typing import Any

from ..settings.collection import SettingsCollectorBindings
from ..settings.restoration import SettingsRestoreBindings
from .apply_controller import ApplyBindings


def make_apply_bindings(
    *,
    db_path: str,
    connection: Any,
    widgets: dict[str, Any],
    sample_scope: Any,
    genome: Any,
    parameters: Any,
    filtered_samples: Any,
    filtered_mag_samples: Any,
    encoding_by_feature: Any,
    send_timing_ping: Any,
    sync_position: Any,
    command_hint: Any,
    plot_state: Any,
    diagnostics: Any,
    data_cache: Any,
    buttons: dict[str, Any],
    placeholder: Any,
    plot_lifecycle: Any,
    enable_timing: bool,
    timing: Any,
    set_operation: Any,
) -> ApplyBindings:
    return ApplyBindings(
        _encoding_by_feature=encoding_by_feature,
        _get_filtered_samples_for_contig=filtered_samples,
        _get_filtered_samples_for_mag=filtered_mag_samples,
        _mag_sort_category_sources=parameters.mag_category_sources,
        _sample_sort_category_sources=parameters.sample_category_sources,
        _send_timing_ping=send_timing_ping,
        _sync_from_to_for_selected_contig=sync_position,
        apply_annotation_rules_cbg=genome.apply_annotation_rules,
        combined_features_cbg=genome.combined_features,
        command_hint_pane=command_hint,
        conn=connection,
        current_plot_state=plot_state,
        custom_color_rows=genome.custom_color_rows,
        db_path=db_path,
        diagnostics=diagnostics,
        data_cache=data_cache,
        download_data_button=buttons["data"],
        download_mag_metrics_button=buttons["mag_metrics"],
        download_metrics_button=buttons["contig_metrics"],
        enable_timing=enable_timing,
        feature_label_select=genome.feature_label,
        feature_type_multichoice=genome.feature_types,
        from_position_input=genome.from_position,
        genemap_height_input=parameters.genemap_height,
        mag_params_category_select=parameters.mag_category,
        mag_params_direction=parameters.mag_direction,
        mag_params_metric_select=parameters.mag_metric,
        mag_params_sort_sample_select=parameters.mag_sort_sample,
        mag_track_color_rows=genome.mag_color_rows,
        mag_track_max_dots_input=parameters.mag_max_dots,
        main_placeholder=placeholder,
        max_binning_window_input=parameters.max_binning_window,
        max_genemap_window_input=parameters.max_genemap_window,
        max_samples_input=parameters.max_samples,
        max_sequence_window_input=parameters.max_sequence_window,
        min_coverage_freq_input=parameters.min_coverage_freq,
        peruse_button=buttons["peruse"],
        plot_isoforms_cbg=genome.plot_isoforms,
        plot_lifecycle=plot_lifecycle,
        same_y_scale_cbg=parameters.same_y_scale,
        sample_order_category_select=parameters.sample_order_category,
        sample_order_direction=parameters.sample_order_direction,
        sample_order_metric_select=parameters.sample_order_metric,
        sequence_cbg=genome.sequence,
        sequence_height_input=parameters.sequence_height,
        subplot_height_input=parameters.subplot_height,
        to_position_input=genome.to_position,
        translated_sequence_cbg=genome.translated_sequence,
        translated_sequence_height_input=parameters.translated_sequence_height,
        views=sample_scope,
        widgets=widgets,
        timing=timing,
        set_operation=set_operation,
    )


def make_settings_collector_bindings(
    db_path: str, widgets: dict[str, Any], sample_scope: Any, genome: Any, parameters: Any, filtering: Any
) -> SettingsCollectorBindings:
    return SettingsCollectorBindings(
        apply_annotation_rules_cbg=genome.apply_annotation_rules,
        combined_features_cbg=genome.combined_features,
        custom_color_rows=genome.custom_color_rows,
        db_path=db_path,
        feature_label_select=genome.feature_label,
        feature_type_multichoice=genome.feature_types,
        from_position_input=genome.from_position,
        genemap_height_input=parameters.genemap_height,
        genome_master_cbg=genome.genome_master,
        inter_section_selects=filtering.inter_section_selects,
        mag_params_category_select=parameters.mag_category,
        mag_params_direction=parameters.mag_direction,
        mag_params_metric_select=parameters.mag_metric,
        mag_params_sort_sample_select=parameters.mag_sort_sample,
        mag_track_color_rows=genome.mag_color_rows,
        mag_track_max_dots_input=parameters.mag_max_dots,
        max_binning_window_input=parameters.max_binning_window,
        max_genemap_window_input=parameters.max_genemap_window,
        max_samples_input=parameters.max_samples,
        max_sequence_window_input=parameters.max_sequence_window,
        min_coverage_freq_input=parameters.min_coverage_freq,
        or_sections=filtering.sections,
        plot_isoforms_cbg=genome.plot_isoforms,
        same_y_scale_cbg=parameters.same_y_scale,
        sample_order_category_select=parameters.sample_order_category,
        sample_order_direction=parameters.sample_order_direction,
        sample_order_metric_select=parameters.sample_order_metric,
        sequence_cbg=genome.sequence,
        sequence_height_input=parameters.sequence_height,
        subplot_height_input=parameters.subplot_height,
        to_position_input=genome.to_position,
        translated_sequence_cbg=genome.translated_sequence,
        translated_sequence_height_input=parameters.translated_sequence_height,
        views=sample_scope,
        widgets=widgets,
    )


def make_settings_restore_bindings(
    *,
    widgets: dict[str, Any],
    sample_scope: Any,
    genome: Any,
    parameters: Any,
    filtering: Any,
    filtering_metadata: Any,
    create_query_row: Any,
) -> SettingsRestoreBindings:
    return SettingsRestoreBindings(
        apply_annotation_rules_cbg=genome.apply_annotation_rules,
        color_qualifier_options=genome.color_qualifier_options,
        combined_features_cbg=genome.combined_features,
        create_color_row=genome.create_color_row,
        create_or_section=filtering.create_section,
        create_query_row=create_query_row,
        custom_color_rows=genome.custom_color_rows,
        feature_label_select=genome.feature_label,
        feature_type_multichoice=genome.feature_types,
        filtering_metadata=filtering_metadata,
        from_position_input=genome.from_position,
        genemap_height_input=parameters.genemap_height,
        genome_master_cbg=genome.genome_master,
        inter_section_selects=filtering.inter_section_selects,
        mag_params_category_select=parameters.mag_category,
        mag_params_direction=parameters.mag_direction,
        mag_params_metric_select=parameters.mag_metric,
        mag_params_sort_sample_select=parameters.mag_sort_sample,
        mag_track_color_rows=genome.mag_color_rows,
        mag_track_max_dots_input=parameters.mag_max_dots,
        max_binning_window_input=parameters.max_binning_window,
        max_genemap_window_input=parameters.max_genemap_window,
        max_samples_input=parameters.max_samples,
        max_sequence_window_input=parameters.max_sequence_window,
        min_coverage_freq_input=parameters.min_coverage_freq,
        or_sections=filtering.sections,
        plot_isoforms_cbg=genome.plot_isoforms,
        rebuild_color_rows=genome.rebuild_color_rows,
        rebuild_filtering_content=filtering.rebuild_content,
        rebuild_mag_track_color_rows=genome.rebuild_mag_color_rows,
        rebuild_section=filtering.rebuild_section,
        same_y_scale_cbg=parameters.same_y_scale,
        sample_order_category_select=parameters.sample_order_category,
        sample_order_direction=parameters.sample_order_direction,
        sample_order_metric_select=parameters.sample_order_metric,
        sequence_cbg=genome.sequence,
        sequence_height_input=parameters.sequence_height,
        subplot_height_input=parameters.subplot_height,
        to_position_input=genome.to_position,
        translated_sequence_cbg=genome.translated_sequence,
        translated_sequence_height_input=parameters.translated_sequence_height,
        views=sample_scope,
        widgets=widgets,
    )
