"""Database- and renderer-independent plotting defaults."""

DEFAULT_MAX_BASE_RESOLUTION = 10_000
DEFAULT_GENEMAP_WINDOW = 100_000
DEFAULT_SEQUENCE_WINDOW = 1_000
DEFAULT_MIN_COVERAGE_FREQUENCY = 0.0
DEFAULT_GENEMAP_HEIGHT = 100
DEFAULT_SEQUENCE_HEIGHT = 50
DEFAULT_TRANSLATED_SEQUENCE_HEIGHT = 50
DEFAULT_SUBPLOT_HEIGHT = 100
DEFAULT_MAG_ORDER_DIRECTION = 1
DEFAULT_MAG_MAX_DOTS = 1_000
DEFAULT_MAX_SAMPLES = 20
DEFAULT_SAMPLE_ORDER_DIRECTION = 0
AUTOCOMPLETE_LIMIT = 100
